### PR TITLE
improve phpdoc

### PR DESCRIPTION
**Pull request by loic425**

### CODE REVIEW

**Review by Zales0123 — CHANGES_REQUESTED** [review]
To be honest, I'm not sure about this change. All these docblocks has become redundant with the introduction of scalar types and return types. I intentionally deleted them during extraction, as I see no value in keeping them. What is the reason of this change @loic425? Maybe you can give me another perspective :)

**Comment by loic425** [comment]
@Zales0123 Ok if  you intentionnaly deleted them. I wanted to not loose information by deleting them on sylius.

**Comment by loic425** [comment]
@Zales0123 https://dev.to/jamesking56/is-phpdoc-now-redundant-2jp

**Comment by Zales0123** [comment]
I agree that PHPDocs can be still useful sometimes (specifying types in the array, explaining thrown exception etc.). However, I would avoid them for types and return types declaration, as it's just a duplicated information in the code.

Anyway, thanks for your contribution, feel free to continue this discussion if anything is unclear :)

**Pull request closed without merging**
